source 'https://rubygems.org'
gem 'rails', '= 6.1.7.3'
gem 'mysql2', '>= 0.3.18', '< 0.5'
gem 'puma', '~> 4.3', '>= 4.3.12'
gem 'sass-rails', '~> 6.0', '>= 6.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2', '>= 4.2.2'
gem 'jquery-rails', '>= 4.4.0'
gem 'turbolinks', '~> 5'
gem 'haml', '>= 5.0.0'
gem 'nifty-utils'
gem 'nilify_blanks'
gem 'kaminari', '>= 1.2.1'
gem 'bcrypt'
gem 'foreman'
gem 'hashie'
gem 'authie', '~> 3.0'
gem 'dynamic_form'
gem 'changey', '>= 1.1.0'
gem 'mail'
gem 'autoprefixer-rails'
gem 'bunny', '~> 2.5.1'
gem 'secure_headers', '>= 3.9.0'
gem 'chronic'
gem 'basic_ssl'
gem 'clockwork'
gem 'encrypto_signo'
gem 'epoll', :require => nil
gem 'mongo'
gem 'sentry-raven'
gem 'gelf'
gem 'moonrope', :git => 'https://github.com/adamcooke/moonrope', :branch => 'master'
gem 'jwt'
gem 'createsend', '~> 4.1', '>= 4.1.1'
gem 'acme-client', :git => 'https://github.com/unixcharles/acme-client'

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console'
  gem 'annotate', '>= 2.7.5'
end
